"""Rebuild the Walters oval badge as vector outlines.

    python3 tools/mklogo.py          # rewrites logo_paths.py

The mark on their vans and shirts is a solid oval carrying WALTERS in a heavy
oblique grotesque with EXTERMINATING SERVICE condensed underneath. Measuring the
photographed mark (_source-photos/004.jpg, the van door) gives a width-to-cap
ratio of 4.37 for WALTERS and 11.20 for the sub line, which matches Impact
(4.60 / 12.19) and nothing else on the system. Impact is the classic vinyl-sign
face, so that is almost certainly what the sign shop used. We set the two lines
in Impact, shear them ~11.6 degrees, convert every glyph to an outline and drop
the font dependency: the badge is then pure <path> data, sharp at any size, with
no webfont to load and nothing to go blurry.

Geometry, all measured off the photo. Horizontal foreshortening cancels out of
the width RATIOS, so only the oval's own aspect needed a perspective correction
(1.97 as photographed, 2.05 flat on).

    WALTERS   cap 0.338 of oval height, width 0.735 of oval width, baseline 0.545
    sub line  cap 0.143 of oval height, width 0.780 of oval width, baseline 0.752
"""
import os
import sys

from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.misc.transform import Transform

FONT = '/System/Library/Fonts/Supplemental/Impact.ttf'
SLANT = 0.205  # ~11.6 degrees, matches the photographed mark
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'logo_paths.py')

_font = TTFont(FONT)
_upem = _font['head'].unitsPerEm
_cmap = _font.getBestCmap()
_gs = _font.getGlyphSet()
_hmtx = _font['hmtx']

_bp = BoundsPen(_gs)
_gs[_cmap[ord('W')]].draw(_bp)
CAP = float(_bp.bounds[3])  # cap height, read straight off the W


def _num(v):
    return f'{v:.2f}'.rstrip('0').rstrip('.')


def _layout(text, tracking):
    out, x = [], 0.0
    for ch in text:
        gname = _cmap.get(ord(ch))
        if gname is None:
            raise SystemExit(f'no glyph for {ch!r}')
        if ch != ' ':
            out.append((gname, x))
        x += _hmtx[gname][0] + tracking * _upem
    return out


def word(text, cap, tracking=0.0, squeeze=1.0, slant=SLANT):
    """Set `text` with its baseline at y=0, already sheared. -> (d, width, x_min)."""
    s = cap / CAP
    shear = Transform(1, 0, -slant, 1, 0, 0)
    parts = []
    bounds = BoundsPen(_gs)
    for gname, x in _layout(text, tracking):
        t = shear.transform(Transform().scale(s * squeeze, -s).translate(x, 0))
        sp = SVGPathPen(_gs, ntos=_num)
        _gs[gname].draw(TransformPen(sp, t))
        if sp.getCommands():
            parts.append(sp.getCommands())
        _gs[gname].draw(TransformPen(bounds, t))
    x0, _, x1, _ = bounds.bounds
    return ' '.join(parts), x1 - x0, x0


def line(text, target_w, cap_guess, cx, baseline, tracking=0.0, squeeze=1.0):
    """Set a line, scale it to exactly target_w, centre it on cx, sit it on baseline."""
    d, w, x0 = word(text, cap_guess, tracking, squeeze)
    k = target_w / w
    dx = cx - (x0 + w / 2) * k
    return f'<path d="{d}" transform="translate({dx:.2f} {baseline:.2f}) scale({k:.5f})"/>'


def main():
    W = 640.0
    H = round(W / 2.05, 2)
    cx = W / 2

    main_line = line('WALTERS', target_w=W * 0.735, cap_guess=100,
                     cx=cx, baseline=H * 0.545)
    sub_line = line('EXTERMINATING SERVICE', target_w=W * 0.780, cap_guess=40,
                    cx=cx, baseline=H * 0.752)
    # Standalone W for the favicon and app icon, baseline at 0, cap height 100.
    mono, mono_w, mono_x0 = word('W', 100)

    with open(OUT, 'w') as f:
        f.write(f'''"""Vector outlines of the Walters oval badge. GENERATED by tools/mklogo.py.

Rebuilt from the mark photographed on the company van. The glyphs are outlines,
so the badge stays sharp at any size with no webfont and nothing to blur.
Do not hand edit: run `python3 tools/mklogo.py` instead.
"""

OVAL_W = {W}
OVAL_H = {H}

# Both lines, white, with centring and baselines already baked in.
LETTERS = """{main_line}
{sub_line}"""

# Just the W, cap height 100, baseline at y=0, left edge at x={mono_x0:.2f}.
MONO = """<path d="{mono}"/>"""
MONO_W = {mono_w:.2f}
MONO_X0 = {mono_x0:.2f}
''')
    print(f'wrote {os.path.relpath(OUT, ROOT)}: oval {W} x {H}')


if __name__ == '__main__':
    sys.exit(main())
